### PR TITLE
Move to chai 1.9.2 to match konacha-chai-matchers sinon-chai requirements

### PR DESCRIPTION
**Pull request by outdooricon**

### CODE REVIEW

**Comment by jfirebaugh** [comment]
Thanks for the contribution. There are some additional changes needed to complete this:

* Run `bundle exec rake assets`
* See if any tests need updating

If we can update to the latest chai that'd be even better. See #201 -- but 3.0.0 is the latest now.

**Comment by outdooricon** [comment]
Unfortunately I don't have the resources right now to do a major upgrade to chai, I was just hoping to get this in so that sinon-chai would work...

- `rake assets` completed
- Looks like tests are good

**Comment by jfirebaugh** [comment]
Thanks, even a patch release upgrade is helpful. Committed as cffcd729d34cdc3fbbcde99b9bcb4e17f732cf92.

**Comment by outdooricon** [comment]
Woot, thanks!

**Pull request closed without merging**
