### PR TITLE
Add Support for Sprockets 3.0

### PR DESCRIPTION
**Pull request by alexkravets**

### CODE REVIEW

**Comment by jfirebaugh** [comment]
Thanks @alexkravets. Where does this stand with respect to https://github.com/jfirebaugh/konacha/issues/216#issuecomment-178960198?

**Comment by alexkravets** [comment]
@jfirebaugh no backward compatibility for `sprockets-rails < 3.0`. So seems like `Rails 4.1` is not an option, as that one has `sprockets-rails ~> 2.0`. Correct me if I'm wrong.

**Comment by jfirebaugh** [comment]
Ok, I can't accept this PR as-is then. Konacha needs to maintain compatibility with Rails 4.1.

**Comment by alexkravets** [comment]
@jfirebaugh do you want me to bump version?

**Comment by jfirebaugh** [comment]
@alexkravets Which version are you referring to?

**Comment by alexkravets** [comment]
@jfirebaugh we can bump konacha major version, so for `Rails 4.1` support you would need to keep the current one locked.

**Comment by jfirebaugh** [comment]
No -- I want to maintain Rails 4.1 and sprockets 2 support:

* No changes to `konacha.gemspec`
* Add `Gemfile-rails42-sprockets2` with    <code>
    gem "railties", "~> 4.2.0"
    gem "sprockets-rails", "~> 2.0"
    </code>
* Conditionalize any additions that depend on a sprockets 3 API

**Comment by alexkravets** [comment]
@jfirebaugh we have no interest to do that.

**Comment by jfirebaugh** [comment]
Ok, sorry but I can't accept this PR in that case.

**Comment by alexkravets** [comment]
No problem.

**Comment by rafamanzo** [comment]
@alexkravets I hope you don't mind but I've made a patch that adds the conditionals for sprockets 3 API and undo konacha.gemspec modifications: https://gist.github.com/rafamanzo/4deafb6546ffd350a689

I hope you can apply it, so @jfirebaugh can reopen and accept this. It you are really not interested on it do you mind if a open a new PR with such changes?

Thanks!

**Comment by alexkravets** [comment]
@rafamanzo new pull request has been created: https://github.com/jfirebaugh/konacha/pull/219 — with your patch applied, thanks!

@jfirebaugh please take a look, now this should be good to go!

**Pull request closed without merging**
