### PR TITLE
Add Support for Sprocket Rails 3.0

### PR DESCRIPTION
**Pull request by hugocorbucci**
This should be compatible with the following:
- Rails 4.2, sprockets 3, sprockets-rails 3
- Rails 4.1, sprockets 3, sprockets-rails 3
- Rails 4.2, sprockets 2, sprockets-rails 2
- Rails 4.2, sprockets 3, sprockets-rails 2

This is based on the work that  @alexkravets did and resulted in https://github.com/jfirebaugh/konacha/pull/219. My commits (which could be cleaned up) makes all of it backwards compatible with sprockets-rails-2 (all the way to 2.0.0) and sprockets 3.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
:clap: :clap: :clap:

Just tried this against my app using Rails 4.2 + sprockets 3 + plus both sprockets-rails 2 and 3, and it's working great!!

**Comment by alexkravets** [comment]
Great work!

**Comment by hugocorbucci** [comment]
Alright... I squashed my useless commits to make the history a little better and left @alexkravets commit in there.

**Comment by jfirebaugh** [comment]
Fixed in 71b47cc2007d991be5cfcd31d719fd14a15847cb and 857dd37721158b7287b1b0d06a638b03e27907dc and will be released in 4.0 shortly. Thanks everyone!

**Pull request closed without merging**
