### PR TITLE
Add Rails 5 Support

### PR DESCRIPTION
**Pull request by tarebyte**
👋

Closes https://github.com/jfirebaugh/konacha/issues/230

I've added Rails 5 and Ruby 2.3.1 to the Travis testing Matrix and added support for Rails 5.

Thanks!

### CODE REVIEW

**Comment by tarebyte** [comment]
So it looks like something changed in the Travis CI config that stopped selenium from working.

Here is a separate build I ran here: https://travis-ci.org/tarebyte/konacha/builds/175511362 that just added Ruby 2.3.1 to the matrix.

I think there is a bigger issue here, and I'll try to come back to it when I have time.

Sorry for the noise!

**Comment by jfirebaugh** [comment]
Thanks @tarebyte! Sorry about the build failures. It looks like they were due to picking up a new major version release of selenium-webdriver that isn't compatible with something. I don't have time to sort through what the incompatibility is so I just pinned to `~> 2`. Want to rebase on master and see if it builds now?

**Comment by maletor** [comment]
This looks perfect to me. @jfirebaugh, can we get this merged in and cut a new release?

**Comment by jfirebaugh** [comment]
Sure, but we'll need it to be passing CI first.

**Comment by maletor** [comment]
So if re-run master on travis right now it is totally green?

**Comment by maletor** [comment]
Anything I can help with @tarebyte?

**Comment by tarebyte** [comment]
> Anything I can help with @tarebyte?

@maletor I kept playing with it, not sure what's up. If you want to take over this PR feel free this isn't very high up on my priority list.

I can give you access to my fork just let me know.

**Comment by dpoint01** [comment]
@tarebyte any update on this ?

**Comment by tarebyte** [comment]
@dpoint01 this fell off my radar, I'll try and take a look at it soon.

**Comment by tarebyte** [comment]
Closing this to being stale, apologies for dropping the ball on this.

**Pull request closed without merging**
